### ISSUE TITLE
fn._ should support casting to string in order to debug functions

### ISSUE THREAD

**Issue by kachayev** [kachayev/fn.py#10]
I.e.

``` python
>>> print (_ * 2)
"(x1) => x1 * 2"
>>> print (_ + _)
"(x1, x2) => x1 + x2"
```

**Comment by K900** [comment]
Is there anything else needed for this except cab56e40235befde5ca1c10556f11c357ff3eaa2 ?

**Comment by kachayev** [comment]
Yes, I added recursive string builder for more than two argument (with appropriate test cases) + readme + history + version. Everything is done in https://github.com/kachayev/fn.py/commit/36c3e064f81620cfef146f803d882e8435f6dd4f, so I'm closing this issue.
