### ISSUE TITLE
(question) Folds implementation and reduce()

### ISSUE THREAD

**Issue by K900** [kachayev/fn.py#18]
I want to add foldl and foldr tomorrow, but I feel like this needs some discussion. CPython's builtin reduce() is a left-fold. Can/should we rely on this or should it be replaced with a custom left-fold implementation? reduce() should be faster, but the actual result of it is up to the implementation if I understand correctly.

**Comment by kachayev** [comment]
Actually, I thought about `foldl`, `foldr` as about operator. Something like:

``` python
>>> from fn import op, _
>>> op.foldl(_ + _)([1,2,3])
6
>>> folder = op.foldr(_ * _, 1)
>>> folder([1,2,3])
6
```

**Comment by K900** [comment]
I like that one. Will update my code before pushing then. Probably tomorrow.

**Comment by kachayev** [comment]
Ok, thanks for help! 
Just link your pull request to this issue.

**Comment by kachayev** [comment]
Close this task in https://github.com/kachayev/fn.py/commit/8e9362825bb545dd3ae1fa3cec9eaef5fd3823f5
