### ISSUE TITLE
about rock tail recursion

### ISSUE THREAD

**Issue by pyloque** [kachayev/fn.py#28]
---

@tail_call_optimized
def even(x):
    if x == 0: return True
    return odd(x-1)

@tail_call_optimized
def odd(x):
    if x == 0: return False
    return even(x-1)

print even(100000)

can recur.tco resolve rock tail recursion? 

---

**Comment by kachayev** [comment]
Sure,

``` python
>>> from fn import recur
>>> @recur.tco
... def even(x):
...     if x == 0: return False, True
...     return odd, (x-1,)
... 
>>> @recur.tco
... def odd(x):
...     if x == 0: return False, False
...     return even, (x-1,)
... 
>>> print even(100000)
True
```

**Comment by kachayev** [comment]
I think I should add this example to the documentation.

**Comment by kachayev** [comment]
I add this example to documentation with this commit: https://github.com/kachayev/fn.py/commit/14c3a8d7a30624caa873c8c030c1f965cb9f5dde Closing issue, if I can do something else regarding this question, please reopen it.

**Comment by pyloque** [comment]
Thank U.
