### ISSUE TITLE
iters.flatten attempts to flatten dict

### ISSUE THREAD

**Issue by pedroteixeira** [kachayev/fn.py#34]
Hi, It's quite misleading that flatten does not ignore dictionaries. 

For instance, the following snippet is not expected for most flatten arounds.

```
In: list(iters.flatten([{'a':1}]))
Out: ['a']
```

It seems more useful to have it return [{'a': 1}] in this case.

**Comment by kachayev** [comment]
It's absolutely valid for Python, cause of default dictionary iterator (over keys):

``` python
>>> list({'a': 1})
['a']
```

**Comment by pedroteixeira** [comment]
oh, this is quite unexpected for me also! I guess I'm just used to how clojure flatten and list works :)
