### ISSUE TITLE
Define second and ffisrt functions

### ISSUE THREAD

**Issue by kachayev** [kachayev/fn.py#41]

**Comment by microamp** [comment]
```
second = F(rest) >> first
```

may be more intuitive than the previously suggested implementation,

```
second = partial(nth, 2)
```

Also, that would be more consistent with

```
ffirst = F(first) >> first
```

**Comment by kachayev** [comment]
Yes, it's a good example of using function composition :)

**Comment by microamp** [comment]
Cool. Please feel free to let me know if you'd like me to add them in unless you've already started working on it. I will update the doc and tests accordingly as well. Thanks! :)

P.S. I am super excited about the persistent data structures being implemented. Keep up the good work, sir.

**Comment by kachayev** [comment]
> you've already started working on it

No, I didn't start. Just not I'm totally focused on persistent data structures. As far as I understood, will wait for PR from you.

>  I am super excited about the persistent data structures being implemented.

Thanks!

**Comment by microamp** [comment]
No problem. Will create a PR when ready. Thanks.
