### ISSUE TITLE
how to use _ in a function

### ISSUE THREAD

**Issue by laocan** [kachayev/fn.py#64]
I've try : 
  print math.sin(_)
it turn out to be wrong, but it works for:
  lambda x: math.sin(x)

Does _ always be same as lambda caluse?
any limitation?
thx ~~

**Comment by kachayev** [comment]
@laocan There is no way in Python to work with expressions like `math.sin(_)` cause of evaluation order. And, btw, there is no necessity for doing this in you example.  `math.sin(_)` most probably means `lambda x: math.sin(x)` which is equivalent to `math.sin`.

**Comment by microamp** [comment]
I would also like to suggest having a look at the [tests](https://github.com/kachayev/fn.py/blob/master/tests.py#L75). It does cover most of `operator`s (e.g. `operator.add`). It also handles method calls as well as some neat stuff like slices!

**Comment by kachayev** [comment]
BTW, If you need to express `math.ldexp(10, _)` use `partial(math.ldexp, 10)`. If you need `math.ldexp(_, 10)` use `partial(flip(math.ldexp), 10)`.

Is there something else that I can help you with?

**Comment by laocan** [comment]
I got it.
thx~
